name: recommender
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - jupyter
  - pip:
      - polars
      - pymysql
      - sqlalchemy
      - pyyaml
      - pyarrow
      - qdrant-client

# - torch
# - --extra-index-url https://download.pytorch.org/whl/cu118
